### ISSUE TITLE
Error with lite version of plugin

### ISSUE THREAD

**Issue by piotrpog** [ryssbowh/bootstrap-theme#1]
Clean Craft install, only theme plugin and bootstrap theme installed. When lite version of plugin is enabled and i try to add new entry, error shows up. This error does not show up when i enable pro version of plugin.

Twig\Error\RuntimeError: Impossible to access an attribute ("viewModes") on a null variable. in C:\xampp8\htdocs\test_themes\vendor\ryssbowh\craft-themes\src\templates\cp\element-shortcuts.twig:24

System info:

PHP version 	8.1.2
OS version 	WINNT 10.0
Database driver & version 	MySQL 5.5.5
Image driver & version 	GD 8.1.2
Craft edition & version 	Craft Solo 4.2.0.2
Yii version 	2.0.45
Twig version 	v3.3.10
Guzzle version 	7.4.5

**Comment by ryssbowh** [comment]
Hi thanks for reporting,

This is fixed in 4.2.2
